dist: xenial
language: python
python: 3.6
install:
  - pip install -r requirements.txt
  - pip install -e .
script:
  - cmsis_posmsk_codegen test.yaml > test.result
  - diff test.result test.expected
