#define CSTF_CTRL_MIN_HOLD_TIME_Pos 8U
#define CSTF_CTRL_MIN_HOLD_TIME_Msk (15UL << CSTF_CTRL_MIN_HOLD_TIME_Pos)
#define CSTF_CTRL_ENS3_Pos          3U
#define CSTF_CTRL_ENS3_Msk          (1UL << CSTF_CTRL_ENS3_Pos)
#define CSTF_CTRL_ENS2_Pos          2U
#define CSTF_CTRL_ENS2_Msk          (1UL << CSTF_CTRL_ENS2_Pos)
#define CSTF_CTRL_ENS1_Pos          1U
#define CSTF_CTRL_ENS1_Msk          (1UL << CSTF_CTRL_ENS1_Pos)
#define CSTF_CTRL_ENS0_Pos          0U
#define CSTF_CTRL_ENS0_Msk          (1UL << CSTF_CTRL_ENS0_Pos)
#define CSTF_PRIORITY_PRIPORT3_Pos  9U
#define CSTF_PRIORITY_PRIPORT3_Msk  (7UL << CSTF_PRIORITY_PRIPORT3_Pos)
#define CSTF_PRIORITY_PRIPORT2_Pos  6U
#define CSTF_PRIORITY_PRIPORT2_Msk  (7UL << CSTF_PRIORITY_PRIPORT2_Pos)
#define CSTF_PRIORITY_PRIPORT1_Pos  3U
#define CSTF_PRIORITY_PRIPORT1_Msk  (7UL << CSTF_PRIORITY_PRIPORT1_Pos)
#define CSTF_PRIORITY_PRIPORT0_Pos  0U
#define CSTF_PRIORITY_PRIPORT0_Msk  (7UL << CSTF_PRIORITY_PRIPORT0_Pos)
#define CSTF_CLAIMSET_CLAIMSET_Pos  0U
#define CSTF_CLAIMSET_CLAIMSET_Msk  (15UL << CSTF_CLAIMSET_CLAIMSET_Pos)
#define CSTF_CLAIMCLR_CLAIMCLR_Pos  0U
#define CSTF_CLAIMCLR_CLAIMCLR_Msk  (15UL << CSTF_CLAIMCLR_CLAIMCLR_Pos)
#define CSTF_LAR_ACCESS_W_Pos       0U
#define CSTF_LAR_ACCESS_W_Msk       (4294967295UL << CSTF_LAR_ACCESS_W_Pos)
#define CSTF_LSR_LOCKTYPE_Pos       2U
#define CSTF_LSR_LOCKTYPE_Msk       (1UL << CSTF_LSR_LOCKTYPE_Pos)
#define CSTF_LSR_LOCKGRANT_Pos      1U
#define CSTF_LSR_LOCKGRANT_Msk      (1UL << CSTF_LSR_LOCKGRANT_Pos)
#define CSTF_LSR_LOCKEXIST_Pos      0U
#define CSTF_LSR_LOCKEXIST_Msk      (1UL << CSTF_LSR_LOCKEXIST_Pos)
#define CSTF_AUTHSTAT_SNID_Pos      6U
#define CSTF_AUTHSTAT_SNID_Msk      (3UL << CSTF_AUTHSTAT_SNID_Pos)
#define CSTF_AUTHSTAT_SID_Pos       4U
#define CSTF_AUTHSTAT_SID_Msk       (3UL << CSTF_AUTHSTAT_SID_Pos)
#define CSTF_AUTHSTAT_NSNID_Pos     2U
#define CSTF_AUTHSTAT_NSNID_Msk     (3UL << CSTF_AUTHSTAT_NSNID_Pos)
#define CSTF_AUTHSTAT_NSID_Pos      0U
#define CSTF_AUTHSTAT_NSID_Msk      (3UL << CSTF_AUTHSTAT_NSID_Pos)
#define CSTF_DEVID_SCHEME_Pos       4U
#define CSTF_DEVID_SCHEME_Msk       (15UL << CSTF_DEVID_SCHEME_Pos)
#define CSTF_DEVID_PORTCNT_Pos      0U
#define CSTF_DEVID_PORTCNT_Msk      (15UL << CSTF_DEVID_PORTCNT_Pos)
