#define SWO_CODR_PRESCALER_Pos    0U
#define SWO_CODR_PRESCALER_Msk    (8191UL << SWO_CODR_PRESCALER_Pos)
#define SWO_SPRR_PPORT_Pos        0U
#define SWO_SPRR_PPORT_Msk        (3UL << SWO_SPRR_PPORT_Pos)
#define SWO_FFSR_FTNONSTOP_Pos    3U
#define SWO_FFSR_FTNONSTOP_Msk    (1UL << SWO_FFSR_FTNONSTOP_Pos)
#define SWO_FFSR_TCPRESENT_Pos    2U
#define SWO_FFSR_TCPRESENT_Msk    (1UL << SWO_FFSR_TCPRESENT_Pos)
#define SWO_FFSR_FTSTOPPED_Pos    1U
#define SWO_FFSR_FTSTOPPED_Msk    (1UL << SWO_FFSR_FTSTOPPED_Pos)
#define SWO_FFSR_FLINPROG_Pos     0U
#define SWO_FFSR_FLINPROG_Msk     (1UL << SWO_FFSR_FLINPROG_Pos)
#define SWO_CLAIMSET_CLAIMSET_Pos 0U
#define SWO_CLAIMSET_CLAIMSET_Msk (15UL << SWO_CLAIMSET_CLAIMSET_Pos)
#define SWO_CLAIMCLR_CLAIMSET_Pos 0U
#define SWO_CLAIMCLR_CLAIMSET_Msk (15UL << SWO_CLAIMCLR_CLAIMSET_Pos)
#define SWO_LAR_ACCESS_W_Pos      0U
#define SWO_LAR_ACCESS_W_Msk      (4294967295UL << SWO_LAR_ACCESS_W_Pos)
#define SWO_LSR_LOCKTYPE_Pos      2U
#define SWO_LSR_LOCKTYPE_Msk      (1UL << SWO_LSR_LOCKTYPE_Pos)
#define SWO_LSR_LOCKGRANT_Pos     1U
#define SWO_LSR_LOCKGRANT_Msk     (1UL << SWO_LSR_LOCKGRANT_Pos)
#define SWO_LSR_LOCKEXIST_Pos     0U
#define SWO_LSR_LOCKEXIST_Msk     (1UL << SWO_LSR_LOCKEXIST_Pos)
#define SWO_AUTHSTAT_SNID_Pos     6U
#define SWO_AUTHSTAT_SNID_Msk     (3UL << SWO_AUTHSTAT_SNID_Pos)
#define SWO_AUTHSTAT_SID_Pos      4U
#define SWO_AUTHSTAT_SID_Msk      (3UL << SWO_AUTHSTAT_SID_Pos)
#define SWO_AUTHSTAT_NSNID_Pos    2U
#define SWO_AUTHSTAT_NSNID_Msk    (3UL << SWO_AUTHSTAT_NSNID_Pos)
#define SWO_AUTHSTAT_NSID_Pos     0U
#define SWO_AUTHSTAT_NSID_Msk     (3UL << SWO_AUTHSTAT_NSID_Pos)
#define SWO_DEVID_SWOUARTNRZ_Pos  11U
#define SWO_DEVID_SWOUARTNRZ_Msk  (1UL << SWO_DEVID_SWOUARTNRZ_Pos)
#define SWO_DEVID_SWOMAN_Pos      10U
#define SWO_DEVID_SWOMAN_Msk      (1UL << SWO_DEVID_SWOMAN_Pos)
#define SWO_DEVID_TCLKDATA_Pos    9U
#define SWO_DEVID_TCLKDATA_Msk    (1UL << SWO_DEVID_TCLKDATA_Pos)
#define SWO_DEVID_FIFOSIZE_Pos    6U
#define SWO_DEVID_FIFOSIZE_Msk    (7UL << SWO_DEVID_FIFOSIZE_Pos)
#define SWO_DEVID_CLKRELAT_Pos    5U
#define SWO_DEVID_CLKRELAT_Msk    (1UL << SWO_DEVID_CLKRELAT_Pos)
#define SWO_DEVID_MUXNUM_Pos      0U
#define SWO_DEVID_MUXNUM_Msk      (31UL << SWO_DEVID_MUXNUM_Pos)
