#define SWTF_CTRL_MIN_HOLD_TIME_Pos 8U
#define SWTF_CTRL_MIN_HOLD_TIME_Msk (15UL << SWTF_CTRL_MIN_HOLD_TIME_Pos)
#define SWTF_CTRL_ENS1_Pos          1U
#define SWTF_CTRL_ENS1_Msk          (1UL << SWTF_CTRL_ENS1_Pos)
#define SWTF_CTRL_ENS0_Pos          0U
#define SWTF_CTRL_ENS0_Msk          (1UL << SWTF_CTRL_ENS0_Pos)
#define SWTF_PRIORITY_PRIPORT1_Pos  3U
#define SWTF_PRIORITY_PRIPORT1_Msk  (7UL << SWTF_PRIORITY_PRIPORT1_Pos)
#define SWTF_PRIORITY_PRIPORT0_Pos  0U
#define SWTF_PRIORITY_PRIPORT0_Msk  (7UL << SWTF_PRIORITY_PRIPORT0_Pos)
#define SWTF_CLAIMSET_CLAIMSET_Pos  0U
#define SWTF_CLAIMSET_CLAIMSET_Msk  (15UL << SWTF_CLAIMSET_CLAIMSET_Pos)
#define SWTF_CLAIMCLR_CLAIMCLR_Pos  0U
#define SWTF_CLAIMCLR_CLAIMCLR_Msk  (15UL << SWTF_CLAIMCLR_CLAIMCLR_Pos)
#define SWTF_LAR_ACCESS_W_Pos       0U
#define SWTF_LAR_ACCESS_W_Msk       (4294967295UL << SWTF_LAR_ACCESS_W_Pos)
#define SWTF_LSR_LOCKTYPE_Pos       2U
#define SWTF_LSR_LOCKTYPE_Msk       (1UL << SWTF_LSR_LOCKTYPE_Pos)
#define SWTF_LSR_LOCKGRANT_Pos      1U
#define SWTF_LSR_LOCKGRANT_Msk      (1UL << SWTF_LSR_LOCKGRANT_Pos)
#define SWTF_LSR_LOCKEXIST_Pos      0U
#define SWTF_LSR_LOCKEXIST_Msk      (1UL << SWTF_LSR_LOCKEXIST_Pos)
#define SWTF_AUTHSTAT_SNID_Pos      6U
#define SWTF_AUTHSTAT_SNID_Msk      (3UL << SWTF_AUTHSTAT_SNID_Pos)
#define SWTF_AUTHSTAT_SID_Pos       4U
#define SWTF_AUTHSTAT_SID_Msk       (3UL << SWTF_AUTHSTAT_SID_Pos)
#define SWTF_AUTHSTAT_NSNID_Pos     2U
#define SWTF_AUTHSTAT_NSNID_Msk     (3UL << SWTF_AUTHSTAT_NSNID_Pos)
#define SWTF_AUTHSTAT_NSID_Pos      0U
#define SWTF_AUTHSTAT_NSID_Msk      (3UL << SWTF_AUTHSTAT_NSID_Pos)
#define SWTF_DEVID_SCHEME_Pos       4U
#define SWTF_DEVID_SCHEME_Msk       (15UL << SWTF_DEVID_SCHEME_Pos)
#define SWTF_DEVID_PORTCNT_Pos      0U
#define SWTF_DEVID_PORTCNT_Msk      (15UL << SWTF_DEVID_PORTCNT_Pos)
